version: "3.7"

services:
  kestrel:
    container_name: foodie
    build:
      context: ./Foodie
    depends_on:
      - db

  db:
    container_name: mssql_db
    user: root
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql/data

  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Nginx.Dockerfile
    depends_on:
      - kestrel
    ports:
      - "80:80"
      - "443:443"

volumes:
  mssql-data:
    driver: local
