version: "3.7"

services:
  kestrel:
    container_name: foodie
    image: "${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}"
    depends_on:
      - db
    restart: always

  db:
    container_name: mssql_db
    user: root
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql/data

  reverseproxy:
    image: nginx
    depends_on:
      - kestrel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/.nginx/fullchain.pem:${CERT_PATH}
      - ${PWD}/.nginx/privkey.pem:${CERT_KEY_PATH}
      - ${PWD}/.nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mssql-data:
    driver: local
