version: '3.7'

services:
  kestrel:
    build:
       context: ./Foodie
    ports:
       - "80:80" 
    depends_on:
             - db

  db:
    container_name: mssql_db
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1433:1433"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    volumes:
      - D:\Projects\AspNetProjects\Foodie\mysqldata:/var/opt/mssql/data
    