version: "3.7"

services:
  kestrel:
    container_name: foodie
    build:
      context: ./Foodie
    depends_on:
      - db
  angular:
    container_name: angular
    ports:
      - 80:4200
    build:
      context: ./Foodie/ClientApp
    volumes:
      - ${PWD}/Foodie/ClientApp/:/app/
      - /app/node_modules
  db:
    container_name: mssql_db
    user: root
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql/data

  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Nginx.Dockerfile
    depends_on:
      - kestrel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/localhost.key:/etc/ssl/private/localhost.key:ro
      - ${PWD}/nginx/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  mssql-data:
    driver: local
