name: deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_NAME_PROXY: ${{ vars.IMAGE_NAME_PROXY }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}

jobs:
  publish-dotnet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build ./Foodie --tag $IMAGE_NAME:${{github.ref_name}}

    - name: Publish image
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
        docker tag $IMAGE_NAME:${{github.ref_name}} $DOCKER_REGISTRY/$IMAGE_NAME:${{github.ref_name}}
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:${{github.ref_name}}

  publish-nginx:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build ./nginx -f ./nginx/Nginx.Dockerfile --tag $IMAGE_NAME_PROXY:${{github.ref_name}}

    - name: Publish image
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
        docker tag $IMAGE_NAME_PROXY:${{github.ref_name}} $DOCKER_REGISTRY/$IMAGE_NAME_PROXY:${{github.ref_name}}
        docker push $DOCKER_REGISTRY/$IMAGE_NAME_PROXY:${{github.ref_name}}
