name: deploy

on: pull_request

env:
  TAG: v0.0.1
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: clone and docker compose up
      uses: appleboy/ssh-action@master
      env:
        CERT_KEY: ${{ secrets.CERT_KEY }}
        CERT_FULLCHAIN: ${{ secrets.CERT_FULLCHAIN }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CERTIFICATE: ${{ secrets.CERTIFICATE }}
        NGINX_CONF: ${{ secrets.NGINX_CONF }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: TAG,IMAGE_NAME,CERT_KEY,CERT_FULLCHAIN,PRIVATE_KEY,CERTIFICATE,NGINX_CONF
        script: |
          rm -rf repo
          git clone https://github.com/${{github.repository}} repo && cd repo
          git fetch origin refs/pull/49/head
          git checkout FETCH_HEAD
          chmod +x ./deploy.sh
          ./deploy.sh
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d
