name: deploy

on: pull_request

env:
  TAG: v0.0.1
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: [publish-dotnet]

    steps:
    - name: clone and docker compose up
      uses: appleboy/ssh-action@master
      env:
        CERT_KEY: ${{ secrets.CERT_KEY }}
        CERT_FULLCHAIN: ${{ secrets.CERT_FULLCHAIN }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CERTIFICATE: ${{ secrets.CERTIFICATE }}
        NGINX_CONF: ${{ secrets.NGINX_CONF }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          rm -rf repo
          git clone https://github.com/${{github.repository}} repo && cd repo
          git fetch origin ${{github.ref_name}}
          git checkout ${{github.ref_name}}
          ./deploy.sh
          docker-compose -f docker-compose.production.yml down
          docker-compose -f docker-compose.production.yml up -d
